name: main
on:
  push:
    branches: ['main']
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.20.1'
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - run: yarn run test
